# 1次元圧縮性Euler方程式
## 支配方程式
$\displaystyle \frac{\partial Q}{\partial t} + \frac{\partial F}{\partial x} = 0$

$\displaystyle e= \frac{1}{2}\rho u^2 + \frac{p}{\gamma-1}$

where  
$Q = \left[
\begin{matrix}
\rho \\ 
\rho u \\
e
\end{matrix}
\right]$

$F = \left[
\begin{matrix}
\rho u \\ 
\rho u^2 + p \\
(E + p)u
\end{matrix}
\right]$

$\rho$ is density of fluid, 
$u$ is flow velocity, 
$e$ is total energy per unit mass, and
$p$ is pressure.

## Flux jacobian
$\displaystyle \frac{\partial F}{\partial Q} = A = P\Lambda P^{-1}$

where 

$\displaystyle P=\left[
\begin{matrix}
1 & 1 & 1 \\ 
u-a & u & u+a \\
H-au & \frac{u^2}{2} & H+au
\end{matrix}
\right]$

$\displaystyle \Lambda = \left[
\begin{matrix}
u-a & 0 & 0 \\ 
0 & u & 0 \\
0 & 0 & u+a
\end{matrix}
\right]$

$\displaystyle P^{-1}=\left[
\begin{matrix}
\frac{1}{2}\left( \alpha_1 + \frac{u}{a} \right) & -\frac{1}{2}\left( \alpha_2 u + \frac{1}{a} \right) & \frac{\alpha_2}{2} \\ 
1-\alpha_1 & \alpha_2u & -\alpha_2 \\
\frac{1}{2}\left( \alpha_1 - \frac{u}{a} \right) & -\frac{1}{2}\left( \alpha_2 u - \frac{1}{a} \right) & \frac{\alpha_2}{2} \\ 
\end{matrix}
\right]$

$\displaystyle \alpha_1 = 
\frac{\left( \gamma - 1 \right) u^2}
{2a^2}$

$\displaystyle \alpha_2 = 
\frac{\left( \gamma - 1 \right)}
{a^2}$

$H$ is total enthalpy, $T$ is temperature, and $a$ is speed of sound.

$\displaystyle H = \rho c_p T = \frac{\gamma}{\gamma - 1} \rho T = \frac{\gamma}{\gamma - 1}p$  
$\displaystyle T = \frac{p}{\rho}$  
$\displaystyle a = \sqrt{ \gamma \frac{p}{\rho} }$


$\gamma = 1.4$ is heat capacity ratio.

## descritization
$\displaystyle \int_\Omega \left( \frac{\partial Q_i}{\partial t} + \frac{\partial F_i}{\partial x} \right) d\Omega= 0$

$\displaystyle \frac{\partial}{\partial t} \int_\Omega Q_i d\Omega + \int_{ \partial \Omega } F_i \vec{n} d\left( \partial \Omega \right)= 0$

$\displaystyle \frac{\partial}{\partial t} \bar{Q} \delta \Omega = - \sum_{ j \in \partial \Omega  } F_{ij} \vec{n}_j \delta (\partial \Omega)_j$

where  
$\displaystyle F_{ij} = \frac{1}{2} \left( F_i + F_j \right) - \frac{1}{2} A^{roe} \left( Q_j - Q_i \right)$

$A^{roe} = P\Lambda P^{-1}$  
Note that $P$, $\Lambda$ and $P^{-1}$ are calculated from the variable of roe average.

### Roe average
$\rho_{roe} = \sqrt{\rho_i \rho_j}$  
$\displaystyle u_{roe} = \frac{\sqrt{\rho_i} u_i + \sqrt{\rho_j} u_j}{\sqrt{\rho_i} + \sqrt{\rho_j} }$  
$\displaystyle H_{roe} = \frac{\sqrt{\rho_i} H_i + \sqrt{\rho_j} H_j}{\sqrt{\rho_i} + \sqrt{\rho_j} }$  
$\displaystyle a_{roe} = \sqrt{ \left( \gamma - 1 \right) \left( H_{roe} - \frac{u_{roe}^2}{2} \right) }$  

where H is total enthalpy per unit volume as below.  
$\displaystyle H = \frac{\left( e + p\right)}{\rho} = \frac{1}{\rho} \left( \frac{1}{2}\rho u^2 + \frac{p}{\gamma-1} + p  \right) = \frac{1}{2}u^{2} + \frac{\gamma}{\gamma-1}\frac{p}{\rho}$

### Coupling
#### Equations of Motion (1D)
$\displaystyle \frac{dX_B}{dt} = a_B X_B + b_B$  
where  
$\displaystyle X_B=\left[
\begin{matrix}
x_B \\ 
u_B
\end{matrix}
\right]$  
$\displaystyle a_B=\left[
\begin{matrix}
0 & 1 \\ 
-\omega_n^2 & -2 \zeta \omega_n
\end{matrix}
\right]$  
$\displaystyle b_B=\left[
\begin{matrix}
0 \\ 
F
\end{matrix}
\right]$  
$\displaystyle F=\frac{f}{m} = \frac{S_B p_B}{m}$  
$\displaystyle \omega_n = \sqrt{\frac{k}{m}}$  
$\displaystyle \zeta = \frac{c}{2\sqrt{mk}}$  

$\displaystyle X_B^{n+1} = \left[ \frac{I}{\Delta t} - \frac{1}{2} a_B \right]^{-1} \left\{ \left[ \frac{I}{\Delta t} + \frac{1}{2} a_B \right] X_B^n + \frac{b^{n+1} + b^n}{2} \right\}$  
$\displaystyle \left[ \frac{I}{\Delta t} - \frac{1}{2} a_B \right]^{-1} = \frac{1}{\left( -\zeta \omega_n + \frac{1}{2} \omega_n^2 + \frac{1}{2} \right) + \frac{1}{4} \omega_n^2 \Delta t } \left[ \begin{matrix}
1 - \zeta \omega_n \Delta t & -1 + \frac{\Delta t}{2} \\ 
-1+\frac{1}{2} \omega_n^2 \Delta t & 1 
\end{matrix}
\right]$  


#### boundary condition on object surface
$\displaystyle \frac{1}{\Delta t} \left[ \left( \rho u \right)_{B-\frac{1}{4}}^{n+1} \Delta x_B^{n+1} - \left( \rho u \right)_{B-\frac{1}{4}}^{n} \Delta x_B^{n} \right]$
$\displaystyle + \left\{ \left( \rho u^2 + p \right)_{B}^{n+\frac{1}{2}} - \left( \rho u^2 + p \right)_{B-\frac{1}{2}}^{n+\frac{1}{2}} \right\}$
$\displaystyle - \left[ \left( \rho u \right)_{B}^{n+\frac{1}{2}}  \delta x_{B}^{n+1} - \left( \rho u \right)_{B-\frac{1}{2}}^{n+\frac{1}{2}} \delta x_{B-\frac{1}{2}}^{n+1} \right] = 0$  

$\displaystyle \left( \cdot \right)_{B-\frac{1}{2}} = \frac{1}{2} \left\{ \left( \cdot \right)_{B} + \left( \cdot \right)_{B-1} \right\}$  
$\displaystyle \left( \cdot \right)_{B-\frac{1}{4}} = \frac{1}{4} \left\{ 3 \left( \cdot \right)_{B} + \left( \cdot \right)_{B-1} \right\}$  
$\displaystyle \left( \cdot \right)_{B-\frac{1}{4}}^{n+\frac{1}{2}} = \frac{1}{8} \left\{ 3 \left( \cdot \right)_{B}^{n+1} + 3 \left( \cdot \right)_{B}^{n} + \left( \cdot \right)_{B-1}^{n+1} + \left( \cdot \right)_{B-1}^{n} \right\}$  

$\displaystyle p_B^{n+1} = \left\{ \frac{1}{4} \alpha_{B-1}^n u_B^{n+1} \left( 3\Delta x_{B}^{n+1} - \delta x_B^{n+1} \right)+ \frac{1}{4} \left( \alpha_{B-1}^n u_B^{\left(n+1\right)^2}  + 1 \right) \right\}^{-1}$
$\left\{ -\left[ \frac{1}{4} \left(\rho u \right)_{B-1}^{n+1} \Delta x_B^{n+1} - \left(\rho u \right)_{B-\frac{1}{4}}^{n} \Delta x_B^{n} \right]
-\left[ \frac{1}{4} \left(\rho u^2 + p \right)_{B}^{n} - \frac{1}{2} \left( \rho u^2 + p \right)_{B-1}^{n+\frac{1}{2}}\right]
+\left[ \left(\rho u \right)_{B}^{n} \left( \frac{1}{2} \delta x_B^{n+1} - \frac{1}{4} \delta x_{B-\frac{1}{2}}^{n+1} \right) - \frac{1}{2} \left(\rho u \right)_{B-1}^{n+\frac{1}{2}} \delta x_{B-\frac{1}{2}}^{n+\frac{1}{2}} \right] \right\}$  

$\displaystyle \rho_B^{n+1} = \alpha_{B-1}^{n} p_B^{n+1} = \frac{p_B^{n+1}}{p_{B-1}^{n}} \rho_{B-1}^{n} $

In [57]:
# constant
L=3 # [m]
U=5 # [m/s]
P=101325 # [Pa]
Rho = 1.293 # [m^3/kg]
T=298 # [K]

g = 1.4
g1 = g - 1
g3 = g - 3

non_L = 1
non_U = 1
non_A = 1
non_Rho = 1
non_P = non_Rho / g * non_A**2
non_T = non_P / non_Rho
non_e = 1/2 * non_Rho * non_U**2 + non_P / g1
print(non_P)
print(non_e)
def e2p(Q):
    rho = Q[:, 0]
    u = Q[:, 1] / Q[:, 0]
    e = Q[:, 2]
    p = g1 * ( e - 1/2 * rho * u**2 )
    return p

def e2T(Q):
    p = e2p(Q)
    rho = Q[:, 0]
    T = p / rho
    return T

in_Mach = 0.9
in_P = non_P
in_T = non_T

in_Rho = in_P / in_T
in_U = in_Mach
def get_inlet_value():
    return in_Rho, in_U, in_P

0.7142857142857143
2.2857142857142865


In [72]:
Tmax = 3 / (L/U) # [-] non-dimentional time
dt = 0.001
half_n = 50
n = (half_n + 1) * 2
x_B_initial = 0.1
dx = non_L / n
x_c = np.zeros(n)
x_e = np.zeros(n+1)
for j in range(n+1):
    x_e[j] = j * dx
    
for i in range(n):
    x_c[i] = (i + 1 / 2 ) * dx
    
# initial condition
Q = np.zeros((n, 3), np.float64)
Q[:, 0] = non_Rho
Q[:, 1] = non_Rho * 0
Q[:, 2] = 1/2*non_Rho*0**2 + ( non_P ) / g1

obj_i_L = half_n
obj_i_R = half_n + 1

obj_left_j = obj_i_L
obj_center_j = obj_left_j + 1
obj_right_j = obj_left_j + 2

for i in range(n):
    if ( i < obj_i_R ):
        pass
    else:
        Q[i, 0] = 1/8*non_Rho
        Q[i, 2] = 1/2*(1/10*non_Rho)*0**2 + ( non_P / 10 ) / g1


In [73]:

from math import sqrt
import numpy as np

def q2b(q):
    rho = q[0]
    u = q[1] / q[0]
    e = q[2] 
    p = g1 * ( e - (1/2 * rho * u**2) )
    return rho, u, e, p

def q2f(q):
    (rho, u, e, p) = q2b(q)
    F = np.zeros(3)
    F[0] = rho * u
    F[1] = rho * u**2 + p
    F[2] = (e + p) * u
    #F[0] = rho * u
    #F[1] = -g3/2 * rho * u**2 + g1*e
    #F[2] = -g1/2 * rho*u**3 + g*u*e
    return F

def entropy_fix(a, epsilon=0.15):
    abs_a = abs(a)
    if ( abs_a < epsilon ):
        mod_a = 1/2* (abs_a**2/epsilon + epsilon)
    else:
        mod_a = abs_a
    return mod_a

def roe_fds(qi, qj):
    ( rho_i, u_i, e_i, p_i ) = q2b(qi)
    ( rho_j, u_j, e_j, p_j ) = q2b(qj)
    H_i = ( g / g1 ) * p_i / rho_i + u_i**2 / 2
    H_j = ( g / g1 ) * p_j / rho_j + u_j**2 / 2
    
    rho = sqrt(rho_i * rho_j)
    u = ( sqrt(rho_i) * u_i + sqrt(rho_j) * u_j ) / (sqrt(rho_i) + sqrt(rho_j) )
    H = ( sqrt(rho_i) * H_i + sqrt(rho_j) * H_j ) / (sqrt(rho_i) + sqrt(rho_j) )
    a_sq = g1 * ( H - u**2 /2 )
    if a_sq < 0:
        print(qi, qj)
        print(rho, u, H, a_sq)
        raise ValueError
    # a = sqrt( g1 * ( H - u**2/2 ) )
    a = sqrt(a_sq)
    if ( rho_i != rho_j ):
        pass
        # print(rho_i, u_i, e_i, p_i)
        # print(rho_j, u_j, e_j, p_j)
        # print(H_i, H_j, sqrt(rho_i)*H_i, sqrt(rho_j)*H_j, sqrt(rho_i) + sqrt(rho_j), H )
        # print(rho, g1*H/a_sq, a_sq)
    
    P = np.zeros((3,3))
    invP = np.zeros((3,3))
    L = np.zeros((3,3))
    
    a1 = ( g1 * u**2 ) / (2 * a**2)
    a2 = g1 / a**2
    
    P[0, 0] = 1
    P[0, 1] = 1
    P[0, 2] = 1
    P[1, 0] = u - a
    P[1, 1] = u
    P[1, 2] = u + a
    P[2, 0] = H - a * u
    P[2, 1] = u**2 / 2
    P[2, 2] = H + a * u

    L[0, 0] = entropy_fix(u - a)
    L[1, 1] = entropy_fix(u)
    L[2, 2] = entropy_fix(u + a) 
    
    invP[0, 0] = 1/2 * (a1 + u/a)
    invP[0, 1] = -1/2 * (a2*u + 1/a)
    invP[0, 2] = a2 / 2
    invP[1, 0] = 1 - a1
    invP[1, 1] = a2 * u
    invP[1, 2] = -a2
    invP[2, 0] = 1/2*(a1 - u/a)
    invP[2, 1] = -1/2 * (a2*u - 1/a)
    invP[2, 2] = a2 / 2

    dq = qj - qi
    dF = np.dot(P, np.dot(L, np.dot(invP, dq)))
    
    F_i = q2f(qi)
    F_j = q2f(qj)
    #print(qi, qj)
    #print(F_i, F_j)
    roeF = 1/2 * (F_i + F_j) - 1/2*dF
    return roeF  

#### SLAU2 algorithm
$\displaystyle \bar{\rho} = \frac{\rho_L + \rho_R}{2}$  
$\displaystyle \bar{c} = \frac{c_L + c_R}{2}$  
$\displaystyle \hat{M} = min\left( 1, \frac{1}{\bar{c}} \sqrt{ \frac{u_L^2 + u_R^2}{2}}\right)$  

$\displaystyle M_L = \frac{V_{nL}}{\bar{c}} = \frac{\vec{u_L} \bullet \vec{n_L}}{\bar{c}}$  
$\displaystyle M_R = \frac{V_{nR}}{\bar{c}} = \frac{\vec{u_R} \bullet \vec{n_R}}{\bar{c}}$  
$\displaystyle \left| \bar{V_n} \right| = \frac{\rho_L \left| V_{nL} \right| + \rho_R \left| V_{nR} \right| }{\rho_L + \rho_R}$  

$\displaystyle P_L^+ = ...$  
$\displaystyle P_R^- = ...$  
$\displaystyle P^{\pm}|_{\alpha} = \left\{ \begin{array}{ll} \frac{1}{2} \left( 1 \pm sign\left( M \right) \right) & \left( \left| M \right| \ge 1 \right) \\ \frac{1}{4} \left( M \pm 1 \right)^2 \left( 2 \mp M \right) \pm \alpha M \left( M^2 - 1\right)^2 & \left( \left|M\right| \lt 1 \right) \end{array} \right.$  
$\displaystyle \tilde{p} = \frac{p_L + p_R}{2} + \frac{P^+|_{\alpha=0} - P^-|_{\alpha=0}}{2} \left( p_{L} - p_{R} \right) + \gamma_{HR} \sqrt{\frac{u_L^2+u_R^2}{2}} \left( P^+|_{\alpha=0} + P^-|_{\alpha=0} - 1 \right) \bar{\rho} \bar{c}$  

$\displaystyle g = - \left[ max\left\{ min \left( M_L, 0 \right), -1 \right\} \bullet min\left\{ max\left( M_R, 0 \right), 1 \right\} \right]$  
$\displaystyle \chi = \left( 1 - \hat{M}^2 \right) $  

$\displaystyle \left| \bar{V_n} \right|^+ = (1-g)\left| \bar{V_n} \right| + g\left| V_{nL} \right|$  
$\displaystyle \left| \bar{V_n} \right|^- = (1-g)\left| \bar{V_n} \right| + g\left| V_{nR} \right|$  
$\displaystyle \dot{m} = \frac{1}{2} \left\{ \rho_L \left( V_{nL} + \left| \bar{V_n} \right|^+ \right) + \rho_R \left( V_{nR} + \left| \bar{V_n} \right|^- \right)\right\} - \frac{\chi}{\bar{c}} \left( p_R - p_L \right)$  
$\displaystyle E=\frac{\dot{m} + \left| \dot{m} \right|}{2}\psi^ + \frac{\dot{m} - \left| \dot{m} \right|}{2}\psi^- +\tilde{p}\vec{N} $  

In [74]:
def slau2(qi, qj):
    rho_L, u_L, e_L, p_L = q2b(qi)
    rho_R, u_R, e_R, p_R = q2b(qj)
    n_L = 1
    n_R = 1
    H_L = ( g / g1 ) * p_L / rho_L + u_L**2 / 2
    H_R = ( g / g1 ) * p_R / rho_R + u_R**2 / 2

    VnL = u_L * n_L
    VnR = u_R * n_R

    c_L = sqrt(g * p_L / rho_L)
    c_R = sqrt(g * p_R / rho_R)
    
    bar_rho = (rho_L + rho_R) / 2
    # bar_c = (c_L + c_R) / 2 # SLAU
    
    # c12 is interfacial speed of sound  # SLAU2
    c_asterisk2_L = 2*g1/(g+1) * H_L
    c_asterisk2_R = 2*g1/(g+1) * H_R
    tilde_c_L = c_asterisk2_L / max(sqrt(c_asterisk2_L), abs(VnL))
    tilde_c_R = c_asterisk2_R / max(sqrt(c_asterisk2_R), abs(VnR))
    bar_c = min(tilde_c_L, tilde_c_R)
    
    hat_M = min(1, 1/bar_c * sqrt((u_L**2 + u_R**2)/2))
    
    M_L = VnL / bar_c
    M_R = VnR / bar_c
    
    alpha = 0
    if ( abs(M_L) > 1 ):
        Pplus_L = 1/2 * (1 + np.sign(M_L) )
    else:
        Pplus_L = 1/4 * (M_L + 1)**2 * (2 - M_L) + alpha * M_L * (M_L**2 - 1)**2
    
    if ( abs(M_R) > 1 ):
        Pminus_R = 1/2 * (1 - np.sign(M_R) )
    else:
        Pminus_R = 1/4 * (M_R - 1)**2 * (2 + M_R) - alpha * M_R * (M_R**2 - 1)**2
    
    # この値の計算はi-1, j+1が必要なため割愛
    # gamma_w = 1 - np.sign(min(phi_1, phi_2))
    gamma_w = 1    
    gamma_HR = max(0.2 , gamma_w)
    
    tilde_p = (p_L + p_R)/2 + (Pplus_L - Pminus_R)/2 * (p_L - p_R) + gamma_HR * sqrt( (u_L**2 + u_R**2 )/2 ) * (Pplus_L + Pminus_R - 1) * bar_rho * bar_c
    # tilde_p = (p_L + p_R)/2 + (Pplus_L - Pminus_R)/2 * (p_L - p_R) + gamma_HR * sqrt( (u_L**2 + u_R**2 )/2 ) * (Pplus_L + Pminus_R - 1) * bar_rho * c12
    g_slau = -( max( min(M_L, 0), -1 ) * min( max(M_R, 0), 1) )
    chi = (1 - hat_M)**2
    
    abs_Vn = ( rho_L * abs(VnL) + rho_R * abs(VnR) ) / ( rho_L + rho_R )
    Vn_plus = (1-g_slau)*abs_Vn + g_slau * abs(VnL)
    Vn_minus = (1-g_slau)*abs_Vn + g_slau * abs(VnR)
    
    m_dot = 1/2 * ( rho_L * (VnL + Vn_plus) + rho_R * (VnR - Vn_minus) - chi/bar_c * (p_R - p_L) )
    
    psi_L = np.array([1, u_L, H_L])
    psi_R = np.array([1, u_R, H_R])
    N = np.array([0, 1, 0])
    
    F = (m_dot + abs(m_dot))/2 * psi_L + (m_dot - abs(m_dot))/2 * psi_R + tilde_p * N

    return F  


In [75]:
def Q2B(Q):
    B = np.zeros_like(Q)
    Rho = Q[:, 0]
    U = Q[:, 1] / Q[:, 0]
    E = Q[:, 2] 
    P = g1 * ( E - (Rho * U**2 / 2) )
    B[:, 0] = Rho
    B[:, 1] = U
    B[:, 2] = P
    return B

def q2b_wrapper(q):
    rho, u, e, p = q2b(q)
    return np.array([rho, u, p])

def B2Q(B):
    Q = np.zeros_like(B)
    Q[:, 0] = B[:, 0]
    Q[:, 1] = B[:, 0] * B[:, 1]
    Q[:, 2] = 1/2*B[:, 0] * B[:, 1]**2 + B[:, 2] / g1
    return Q

def muscl(Q, qB, qBLR):
    def minmod(p, q, b):
        # print(np.sign(p), abs(p), q*b, min(abs(p), np.sign(p)*q*b))
        return np.sign(p) * max(0, min(abs(p), np.sign(p)*q*b))
    
    B = Q2B(Q)
    
    # 1 と 2 の間を1に格納
    BL = np.zeros((n+1, 3))
    BR = np.zeros((n+1, 3))
    
    qq0 = np.zeros(3)
    qq1 = np.zeros(3)
    qq2 = np.zeros(3)
    k_muscl = 1/3
    b_muscl = 1#(3-k_muscl) / (1-k_muscl)

    for i in range(n):            
        if ( i == obj_i_L ):
            BL[i+1, :] = q2b_wrapper(qBLR[0, :]) # measurement for zero division
            BR[i, :] = q2b_wrapper(qBLR[0, :])
            continue
        elif ( i == obj_i_R ):
            BL[i+1, :] = q2b_wrapper(qBLR[1, :])
            BR[i, :] = q2b_wrapper(qBLR[1, :]) # measurement for zero division
            continue
        
        if ( i == 0 ):
            qq0[0], qq0[1], _, qq0[2] = q2b(qB[:, 0])
        else:
            qq0 = np.array(B[i-1])
            
        qq1 = B[i]
        
        if ( i == n-1 ):
            qq2[0], qq2[1], _, qq2[2] = q2b(qB[:, 1])
        else:
            qq2 = np.array(B[i+1])
        
        for k in range(3):
            dplus_i = qq2[k] - qq1[k]
            dminus_i = qq1[k] - qq0[k]
            
            # i + 1/2
            BL[i+1, k] = qq1[k] + 1/4*(1-k_muscl)*minmod(dminus_i, dplus_i, b_muscl) + 1/4*(1+k_muscl)*minmod(dplus_i, dminus_i, b_muscl)
            # BL[i+1, k] = qq1[k] + 1/4*(1-k_muscl)*dminus_i + 1/4*(1+k_muscl)*dplus_i
            
            # i - 1/2
            BR[i, k] = qq1[k] - 1/4*(1-k_muscl)*minmod(dplus_i, dminus_i, b_muscl) - 1/4*(1+k_muscl)*minmod(dminus_i, dplus_i, b_muscl)
            # BR[i, k] = qq1[k] - 1/4*(1-k_muscl)*dplus_i - 1/4*(1+k_muscl)*dminus_i
    
    # BL[obj_i+1, :] = BR[obj_i+1, :]
    # BR[obj_i, :]   = BL[obj_i, :]
    # BL[0, :] = q2b(qB[:, 0])
    # BR[n, :] = qq2[k]
    # print(Q)
    # print(B)
    QL = B2Q(BL)
    QR = B2Q(BR)

    QL[0, :] = qB[:, 0]
    QR[n, :] = qB[:, 1]
    
    # QL[obj_i+1, :] = qBLR[0]
    # QR[obj_i,   :] = qBLR[1]
    # print(QL)
    # print(QR)
    # print(sqrt(-1))
    return QL, QR

# rrk2(Q)


In [76]:
def fvs(qi, qj):   
    R, R_inv, L, L_abs = A_pm(qi)
    Ap = np.dot(np.dot(R, L+L_abs), R_inv)
    
    R, R_inv, L, L_abs = A_pm(qj)
    Am = np.dot(np.dot(R, L-L_abs), R_inv)
    
    F_plus = 1/2 * ( np.dot(Ap, qi) + np.dot(Am, qj))
    return F_plus

def A_pm(q):
    rho, u, e, p = q2b(q)
    H = (e + p) / rho
    c = sqrt(g1 * (H - u**2 / 2))
    b2 = g1 / c**2
    b1 = (b2 * u**2) / 2
    
    R = np.array([[1, 1, 1], [u-c, u, u+c], [H-u*c, u**2 / 2, H+u*c]])
    R_inv = np.array([[(b1+u/c)/2, (-b2*u-1/c)/2, b2/2],
                      [1-b1, b2*u, -b2], 
                      [(b1-u/c)/2, (-b2*u+1/c) / 2, b2/2]])
    
    L = np.array([[u-c, 0, 0],[0, u, 0],[0, 0, u+c]])
    L_abs = np.array([[abs(u-c), 0, 0],[0, abs(u), 0],[0, 0, abs(u+c)]])
    return R, R_inv, L, L_abs
    


In [77]:
def get_flux(q):
    rho, u, e, p = q2b(q)
    f1 = rho * u
    f2 = rho * u**2 + p
    f3 = (e + p) * u
    f = np.array([f1, f2, f3])
    return f

def flux(Q, qB, qBLR):
    F = np.zeros((n+1, 3))
    if use_muscl:
        QL, QR = muscl(Q, qB, qBLR)
    
    for j in range(n+1):
        # print(j)
        i = j
            
        if ( j == 0 ):
            qi = qB[:, 0]
        elif ( ( j == obj_center_j ) or ( j == obj_right_j ) ):
            qi = Q[j-1, :]
        else:            
            if use_muscl:
                qi = QL[i] # L
            else:
                qi = Q[j-1, :]

        if ( j == n ):
            qj = qB[:, 1]
        elif ( ( j == obj_left_j ) or ( j == obj_center_j ) ):
            qj = Q[j, :]
        else:
            if use_muscl:
                qj = QR[i] # R
            else:
                qj = Q[j  , :]

        # print(f"edge:{j}")
        F[j, :] = slau2(qi, qj)
        # F[j, :] = fvs(qi, qj)
        # if ( qi[0] != qj[0] ):
            # print(j, qi, qj, F[j, :])
        # F[j, :] = roe_fds(qi, qj)
    # sqrt(-1)

    return F


In [78]:
def bc_refrect(q):
    rho, u, e, p = q2b(q)
    qB = np.zeros(3)
    qB[0] = rho
    qB[1] = - rho * u
    qB[2] = e
    return qB

In [79]:
def __bc_nonreflect(q1, q0, dx, dt):
    rho, u, e, p = q2b(q1)
    _, u0, _, p0 = q2b(q0)
    c = sqrt(g * p / rho)
    dpdx = (p - p0)/dx
    dudx = (u - u0)/dx
    
    lam1 = u-c
    lam2 = lam3 = lam4 = u
    lam5 = u+c
    
    L1 = lam1*(dpdx - rho * c * dudx)
    L2 = lam2*(c**2 * dpdx - dpdx)
    L5 = lam5*(dpdx + rho * c * dudx)
    
    d1 = 1/c**2 * (L2 + 1/2 * (L5 + L1) )
    d2 = 1/2 * (L5 + L1)
    d3 = 1/(2*rho*c) * (L5 - L1)
    
    qB = np.zeros(3)
    qB[0] = rho - dt * d1
    qB[1] = rho * u - dt * (u*d1 + rho*d3)
    qB[2] = e - dt * (1/2*u**2*d1 + d2/g1 + rho*u*d3)
    
    return qB

def __bc_inlet(q1):
    _, u, _, p = q2b(q1)
    rho_in, u_in, p_in = get_inlet_value()
    qB = np.zeros(3)
    if ( abs(u) >= 1 ): # supersonic flow    
        pass
    else:
        p_in = p # value from inside
        
    qB[0] = rho_in
    qB[1] = rho_in * u_in
    qB[2] = 1/2*rho_in * u_in**2 + p_in/g1
    return qB

def bc_io(n, q1=None, q0=None, dx=None, dt=None, p_inf=non_P):
    rho, u, e, p = q2b(q1)
    # else: # outlet
    qB = __bc_nonreflect(q1, q0, dx, dt)
    # check
    qB_p = g1 * (qB[2] - 1/2*qB[1]**2/qB[0])
    if ( qB[0] < 0 ) or ( qB[2] < 0 ) or (qB_p < 0):
        print("farfield")
        if ( abs(u) > 1 ):
            pass
        else:
            p = non_P
            e = 1/2 * rho * u**2 + p/g1
        qB = np.array([rho, rho*u, e])
    # print(qB)
    return qB

def bc_inflow(q1, dt, limit_t=0.5):
    rho, u, e, p = q2b(q1)
    rho_in, u_in, p_in = get_inlet_value()
    qB = np.zeros(3)
    if ( abs(u_in) >= 1): # supersonic
        pass
    else:
        p_in = p
    
    # if ( dt < limit_t):
        # u_in = u_in * (dt/limit_t)
        
    qB[0] = rho_in
    qB[1] = rho_in * u_in
    qB[2] = 1/2*rho_in * u_in**2 + p_in/g1
    return qB

In [80]:
def calc_CFL(Q, dx, dt):
    CFL = 0
    for i in range(n):
        qi = Q[i, :]
        ( rho, u, e, p ) = q2b(qi)
        a = sqrt(g * p / rho)
        CFL_i = max(abs(u), abs(u-a), abs(u+a)) * dt / dx[i]
        CFL = max(CFL, CFL_i)
    return CFL

def set_dtau(Q, dx, dt):
    CFL = calc_CFL(Q, dx, dt)
    if ( CFL < 1 ):
        alpha = 2.1
    else:
        alpha = 1.22/CFL - 0.07*CFL + 0.95
    dtau = alpha*dt
    return dtau

### explicit euler
$\displaystyle Q_{i}^{n+1} = Q_{i} - \frac{dt}{\delta \Omega} \sum_{ j \in \partial \Omega  } F_{ij} \vec{n}_j \delta (\partial \Omega)_j$

In [81]:
def update_dx_from_edge(x_e):
    dx = np.diff(x_e)
    return dx

def update_x_from_edge(x_e):
    x_c = np.zeros(n)
    for i in range(n):
        x_c[i] = (x_e[i] + x_e[i+1])/2
    return x_c
   
def update_x_org(t, x_e_0=None, omega=1, coef=0.4, fixed=False):
    x_e = np.zeros(n+1)
    avg_dx = non_L / n
    avg_rad = omega*t
    avg_rad_n = omega*(t-1)
    
    delta_x = np.zeros(n+1)
    for j in range(n+1):
        if fixed or ( j == 0 ) or ( j == n ):
            x_e[j] = j * avg_dx
        else:
            x_e[j] = j * avg_dx + coef*( avg_dx )*np.sin( avg_rad   + j )
            x_e_n  = j * avg_dx + coef*( avg_dx )*np.sin( avg_rad_n + j)
            delta_x[j] = x_e[j] - x_e_n
        
    x_c = update_x_from_edge(x_e)
    dx = update_dx_from_edge(x_e)
    if ( t == 0 ):
        delta_x = np.zeros(n+1)
    return x_c, x_e, dx, delta_x

In [82]:
def get_roe_average(qi, qj):
    ( rho_i, u_i, e_i, p_i ) = q2b(qi)
    ( rho_j, u_j, e_j, p_j ) = q2b(qj)
    H_i = ( g / g1 ) * p_i / rho_i + u_i**2 / 2
    H_j = ( g / g1 ) * p_j / rho_j + u_j**2 / 2
    # print(qi, qj)
    rho = sqrt(rho_i * rho_j)
    u = ( sqrt(rho_i) * u_i + sqrt(rho_j) * u_j ) / (sqrt(rho_i) + sqrt(rho_j) )
    H = ( sqrt(rho_i) * H_i + sqrt(rho_j) * H_j ) / (sqrt(rho_i) + sqrt(rho_j) )
    a_sq = g1 * ( H - u**2 /2 )
    if a_sq < 0:
        print(qi, qj)
        print(rho, u, H, a_sq)
        raise ValueError
    # a = sqrt( g1 * ( H - u**2/2 ) )
    a = sqrt(a_sq)
    return rho, u, H, a

In [83]:
def get_roe_q(qi, qj):
    rho, u, H, a = get_roe_average(qi, qj)
    m = rho*u
    p = a**2 * rho / g
    e = rho*H - p
    return np.array([rho, m, e])   

def roeQ(Q, qB, qBLR):
    roeQ = np.zeros((n+1, 3))
    if use_muscl:
        QL, QR = muscl(Q, qB, qBLR)
        
    for j in range(n+1):
        i = j
        
        if ( j == 0 ):
            qi = qB[:, 0]
        elif ( ( j == obj_center_j ) or ( j == obj_right_j ) ):
            qi = Q[j-1, :]
        else:            
            if use_muscl:
                qi = QL[i] # L
            else:
                qi = Q[j-1, :]

        if ( j == n ):
            qj = qB[:, 1]
        elif ( ( j == obj_left_j ) or ( j == obj_center_j ) ):
            qj = Q[j, :]
        else:
            if use_muscl:
                qj = QR[i] # R
            else:
                qj = Q[j  , :]
                
        rho, u, H, a = get_roe_average(qi, qj)
        m = rho*u
        p = a**2 * rho / g
        e = rho*H - p
        # e = 1/2*rho*u**2 + rho/g1 * (H - u**2/2) # H = (e+p)/rho
        roeQ[j, 0] = rho
        roeQ[j, 1] = m
        roeQ[j, 2] = e
        # print(rho, u, m, H, a, e)

    return roeQ


In [84]:
m_B = 1
omega_B = 1
zeta_B = 1

k_B = omega_B**2 * m_B
c_B = zeta_B * (2 * sqrt(m_B * k_B))

a_B = np.array([[0, 1],[-omega_B**2, -2*zeta_B*omega_B]])
I2 =  np.eye(2)

__M1 = 1/dt *I2 - 1/2 * a_B
det_M1 = __M1[0, 0]*__M1[1, 1] - __M1[0, 1]*__M1[1, 0]
M_1 = 1/det_M1*np.array([[__M1[1,1], - __M1[0, 1]], [- __M1[1, 0], __M1[0, 0]]])
# M_1 = np.linalg.inv(__M1)
M_2 = (1/dt *I2 + 1/2 * a_B)

def motion_eq(x0, u0, p0, p1, A=1, width=0.01):
    xB = x0
    X0 = np.array([0, u0])
    b0 = np.array([0, p0*A / m_B])
    b1 = np.array([0, p1*A / m_B])
    X1 = np.dot(M_1, np.dot(M_2, X0) + (b0 + b1)/2)
    dxB = X1[0]
    u1 = X1[1]
    x1 = x0 + dxB
    return x1, u1

# print(np.dot(M_1, M_2))
motion_eq(0.1, 0, 0, 0)

(0.1, 0.0)

In [85]:
#half = int((n-1)/2) + 1/2
width = 0.01
half_width = width / 2

def set_x_e(position=0.1):
    if ( position < 0 ) or ( position > 1 ):
        raise ValueError
    
    # space = non_L - width
    
    left_space = non_L * position - half_width
    right_space = non_L * (1 - position) - half_width
    
    # scaled_pos = non_L * position # == left
    
    avg_dx0 = left_space / half_n # [0, pos]
    avg_dx1 = right_space / half_n # [pos, 1]

    x_e = np.zeros(n+1)
    for j in range(n+1):
        if j <= obj_left_j:
            x_e[j] = j * avg_dx0
        elif j == obj_center_j:
            x_e[j] = obj_left_j * avg_dx0 + half_width
        else:
            x_e[j] = obj_left_j * avg_dx0 + width + (j - obj_right_j) * avg_dx1
        # print(j, x_e[j])
    return x_e

def set_x_c(position=0.1):
    if ( position < 0 ) or ( position > 1 ):
        raise ValueError
    
    left_space = non_L * position - half_width
    right_space = non_L * (1 - position) - half_width
    
    avg_dx0 = left_space / half # [0, pos]
    avg_dx1 = right_space / half # [pos, 1]

    x_c = np.zeros(n)
    for i in range(n):
        if i <= obj_i_L:
            x_c[i] = (i + 1/2) * avg_dx0
        elif i == obj_i_R:
            x_c[i] = x_c[obj_i_L] + width
        else:
            x_c[i] = x_c[obj_i_R] + width + (i - obj_i_R) * avg_dx1

    return x_c

def update_x_e_from_center(x_c):
    x_e = np.zeros(n+1)
    for j in range(n):
        if j == 0:
            continue
        
        x_e[j] = (x_c[j] + x_c[j-1])/2
    x_e[n] = 1
    return x_e

def update_x_c_from_edge(x_e):
    x_c = np.zeros(n)
    for i in range(n):        
        x_c[i] = (x_e[i] + x_e[i+1])/2
    return x_c

def update_x(Qn, Qn1, x_e_0=None, u_B=None, qBLR0=None, qBLR1=None):
    def get_dp(Q):
        _, ui, _, pi = q2b(Q[obj_i_L, :])
        _, uj, _, pj = q2b(Q[obj_i_R, :])
        dp = - ( pj - pi ) 
        return dp
    
    def qlbr2p(qBLR):
        _, _, _, pL = q2b(qBLR[0])
        _, _, _, pR = q2b(qBLR[1])
        dp = - (pR - pL)
        return dp
    
    if x_e_0 is None:
        x_B = x_B_initial
        u_B1 = 0
        # x_c = set_x_c(x_B)
        x_e = set_x_e(x_B)
        # x_e = update_x_e_from_center(x_c)
        x_c = update_x_c_from_edge(x_e)
        delta_x = np.zeros(n+1)

    else:
        # 物体の運動を解く
        x_B = (x_e_0[obj_left_j] + x_e_0[obj_right_j])/2
        # dpn0 = get_dp(Qn)
        # dpn1 = get_dp(Qn1)
        dpn0 = qlbr2p(qBLR0)
        dpn1 = qlbr2p(qBLR1)
        x_B1, u_B1 = motion_eq(x_B, u_B, dpn0, dpn1)
        # print(f'p0:{dpn0}, p1:{dpn1}')
        # print(f'x_B1:{x_B1}, u_B1:{u_B1}')
        # sqrt(-1)
        x_e = set_x_e(x_B1)
        # x_c = set_x_c(x_B1)
        x_c = update_x_c_from_edge(x_e)
        delta_x = x_e - x_e_0
        
    # x_c = update_x_from_edge(x_e)
    dx = update_dx_from_edge(x_e)
    return x_c, x_e, dx, delta_x, u_B1

# set_x_e(0.2)
update_x_c_from_edge(set_x_e(0.2))
# update_x_e_from_center(set_x_c(0.5))
# x_c, x_e, dx, delta_x, u_B1 = update_x(Q, Q)
# update_x(Q, Q, x_e, u_B1, np.array([Q[0], Q[-1]]), np.array([Q[0], Q[-1]]))

array([0.00195, 0.00585, 0.00975, 0.01365, 0.01755, 0.02145, 0.02535,
       0.02925, 0.03315, 0.03705, 0.04095, 0.04485, 0.04875, 0.05265,
       0.05655, 0.06045, 0.06435, 0.06825, 0.07215, 0.07605, 0.07995,
       0.08385, 0.08775, 0.09165, 0.09555, 0.09945, 0.10335, 0.10725,
       0.11115, 0.11505, 0.11895, 0.12285, 0.12675, 0.13065, 0.13455,
       0.13845, 0.14235, 0.14625, 0.15015, 0.15405, 0.15795, 0.16185,
       0.16575, 0.16965, 0.17355, 0.17745, 0.18135, 0.18525, 0.18915,
       0.19305, 0.1975 , 0.2025 , 0.21295, 0.22885, 0.24475, 0.26065,
       0.27655, 0.29245, 0.30835, 0.32425, 0.34015, 0.35605, 0.37195,
       0.38785, 0.40375, 0.41965, 0.43555, 0.45145, 0.46735, 0.48325,
       0.49915, 0.51505, 0.53095, 0.54685, 0.56275, 0.57865, 0.59455,
       0.61045, 0.62635, 0.64225, 0.65815, 0.67405, 0.68995, 0.70585,
       0.72175, 0.73765, 0.75355, 0.76945, 0.78535, 0.80125, 0.81715,
       0.83305, 0.84895, 0.86485, 0.88075, 0.89665, 0.91255, 0.92845,
       0.94435, 0.96

In [86]:
def __b2q(rho, u, p):
    m = rho*u
    e = 1/2 * rho * u**2 + p / g1
    q = np.array([rho, m, e])
    return q

def update_surface_q(Qn1, Qn, u_B1, dxn1, dxn, delta_x, dt, qBLR):
    def q2bq(q, B=True):
        rho, u, e, p = q2b(q)
        if B:
            u = u_B1
        m = rho * u
        rho_u2 = rho * u**2
        return rho, u, m, rho_u2, p
    
    def get_alpha_org(qB):
        rho, u, m, rho_u2, p = q2bq(qB)
        alpha = rho / p
        return alpha
    
    def get_alpha(qi, qim1):
        rho, u, H, a = get_roe_average(qi, qim1)
        m = rho*u
        p = a**2 * rho / g
        alpha = rho / p
        return alpha
    
    def get_f1(q):
        rho, u, m, rho_u2, p = q2bq(q)
        f1 = rho * u**2 + p
        return f1
    
    def qbl1():
        # leftside
        i = obj_i_L - 1
        B = obj_i_L
        
        qBn0 = np.array(qBLR[0])

        qin0 = Qn[i]
        qin1 = Qn1[i]
        qin12 = 1/2 * (qin0 + qin1)
        
        qi12n0 = 1/2 * (qin0 + qBn0)
        qi34n0 = 1/2 * (qi12n0 + qBn0)

        fin0 = get_flux(qin0)
        fin1 = get_flux(qin1)
        # fin12 = 1/2 * (fin0 + fin1)

        fBn0 = get_flux(qBn0)

        fi12n0 = 1/2 * (fin0 + fBn0)
        
        dxBn0 = 1/2 * (dxn[B])
        dxBn1 = 1/2 * (dxn1[B])

        alpha = get_alpha_org(qin0)
        qc = alpha * u_B1
        fc = alpha * u_B1**2 + 1
        
        delta_x_i = delta_x[obj_left_j]
        delta_x_B = 1/2 * ( delta_x_i + delta_x[obj_center_j] )

        A11 = 1/dt * ( 1/4 * qin1[1] * dxBn1 )
        A12_c = 1/dt * (3/4 * dxBn1 * qc)
        A2 = 1/dt * ( - qi34n0[1] * dxBn0 )

        B11 = 1/2 * fBn0[1] 
        B12_c = 1/2 * fc
        B21 = - 1/2 * fi12n0[1]
        B221 = - 1/4 * fin1[1]
        B222_c = - 1/4 * fc
        
        C11 = -1/dt * ( 1/2 * qBn0[1] * delta_x_B )
        C12_c = -1/dt * ( 1/2 * qc * delta_x_B )
        C21 = -1/dt * ( - 1/2 * qi12n0[1] * delta_x_i )
        C221 = -1/dt * ( - 1/4 * qin1[1] * delta_x_i )
        C222_c = -1/dt * ( - 1/4 * qc * delta_x_i )

        pBn1 = -(A11 + A2 + B11 + B21 + B221 + C11 + C21 + C221) / (A12_c + B12_c + B222_c + C12_c + C222_c)
        rhoBn1 = alpha * pBn1
        qBL1 = __b2q(rhoBn1, u_B1, pBn1)   
        return qBL1
    
    # right side
    def qbr1():
        i = obj_i_R + 1
        B = obj_i_R
        qBn0 = np.array(qBLR[1])

        qin0 = Qn[i]
        qin1 = Qn1[i]
        qin12 = 1/2 * (qin0 + qin1)

        qi12n0 = 1/2 * (qin0 + qBn0)
        qi34n0 = 1/2 * (qi12n0 + qBn0)

        fin0 = get_flux(qin0)
        fin1 = get_flux(qin1)
        # fin12 = 1/2 * (fin0 + fin1)

        fBn0 = get_flux(qBn0)
        fi12n0 = 1/2 * (fin0 + fBn0)

        dxBn0 = 1/2 * (dxn[B])
        dxBn1 = 1/2 * (dxn1[B])

        alpha = get_alpha_org(qin0)
        qc = alpha * u_B1
        fc = alpha * u_B1**2 + 1
        
        delta_x_i = delta_x[obj_right_j]
        delta_x_B = 1/2 * (delta_x[obj_center_j] + delta_x_i)

        A11 = 1/dt * ( 1/4 * qin1[1] * dxBn1 )
        A12_c = 1/dt * (3/4 * dxBn1 * qc)
        A2 = 1/dt * ( - qi34n0[1] * dxBn0 )

        B11 = - 1/2 * fBn0[1] 
        B12_c = - 1/2 * fc
        B21 = 1/2 * fi12n0[1]
        B221 = 1/4 * fin1[1]
        B222_c = 1/4 * fc
        
        C11 = 1/dt * ( 1/2 * qBn0[1] * delta_x_B )
        C12_c = 1/dt * ( 1/2 * qc * delta_x_B )
        C21 = 1/dt * ( - 1/2 * qi12n0[1] * delta_x_i )
        C221 = 1/dt * ( - 1/4 * qin1[1] * delta_x_i )
        C222_c = 1/dt * ( - 1/4 * qc * delta_x_i )

        
        pBn1 = -(A11 + A2 + B11 + B21 + B221 + C11 + C21 + C221) / (A12_c + B12_c + B222_c + C12_c + C222_c)
        rhoBn1 = alpha * pBn1
        qBR1 = __b2q(rhoBn1, u_B1, pBn1)
        
        return qBR1
    # print(qBR1)
    
    qBR1 = qbr1()   
    qBL1 = qbl1()

    return np.array([qBL1, qBR1])

rrk2(Q)
# print("a")

0 13 4.915936538008367e-15 0.5263184618870593 0.0006420729566605902
10 15 7.485339215171958e-15 0.5274079607895893 0.006899567082797487
20 15 7.677872776075055e-15 0.5284118921598577 0.012696075282361864
30 15 8.472793272216803e-15 0.5289382985718692 0.017927285790785872
40 15 3.724812370267098e-15 0.5289683655995114 0.022592972286858946
50 16 2.5685327589240153e-15 0.5286029279614782 0.02674645100880853
60 14 6.2076350975163394e-15 0.5278647997939674 0.030460168307384936
70 15 7.373139979801312e-15 0.526788426186203 0.03379715438291339
80 15 9.10636155586182e-15 0.5254047485021062 0.03681240250878774
90 16 4.342348933918164e-15 0.5237329211060431 0.03958478394255817
100 15 9.888842416258748e-15 0.5217851359303982 0.042196660932242766
110 15 9.791579194048524e-15 0.5195844030224573 0.044712412440499456
120 16 3.776543896998374e-15 0.5171415329516936 0.04715678800722009
130 15 1.8863241967624903e-15 0.5144659789607591 0.04952057748054002
140 15 4.02455504705532e-15 0.5115754847132719 0.

(array([[[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00, ...,
           9.58087929e-01,  9.53313205e-01,  9.48689187e-01],
         [-9.47401080e-33, -2.02923216e-16, -7.02511542e-17, ...,
           3.48436446e-04,  3.43794030e-04,  3.39583522e-04],
         [ 1.78571429e+00,  1.78571429e+00,  1.78571429e+00, ...,
           1.68181996e+00,  1.67009755e+00,  1.65876750e+00]],
 
        [[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00, ...,
           9.58092802e-01,  9.53319271e-01,  9.48693948e-01],
         [-9.22395320e-29,  1.91125535e-16,  3.45414419e-16, ...,
           1.39670713e-03,  1.35623098e-03,  1.32099759e-03],
         [ 1.78571429e+00,  1.78571429e+00,  1.78571429e+00, ...,
           1.68183331e+00,  1.67011375e+00,  1.65878043e+00]],
 
        [[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00, ...,
           9.58104497e-01,  9.53329558e-01,  9.48702277e-01],
         [-6.21930826e-23, -6.53418280e-16, -9.05760209e-17, ...,
           2.26352089e-03,  2.21

In [46]:
def bc_refrect_mod(q, uB):
    rho, u, e, p = q2b(q)
    qB = np.zeros(3)
    qB[0] = rho
    qB[1] = rho * (- u + uB)
    qB[2] = e
    return qB

def update_surface_q_c(Qn1, u_B1, qBLR0):
    qBLR1 = np.zeros_like(qBLR0)
    qBLR1[0, :] = bc_refrect_mod(Qn1[obj_i_L - 1], u_B1)
    qBLR1[1, :] = bc_refrect_mod(Qn1[obj_i_R + 1], u_B1)
    return qBLR1

In [95]:
plot_dt = 100
Nmax = 5000 #int(0.5/dt)#int(Tmax / dt)
Pmax = int(Nmax / plot_dt )
fg = False
use_muscl = True#False#True#False
# paramter for rrk2
b1 = 17
b2 = -16
c2 = 1/32

def q_add_uB(q, uB):
    rho, u, e, p = q2b(q)
    return np.array([rho, rho*uB, e])

def calc_L(Qn1, Qn, dxn1, dxn, delta_x, dt, qBLR0, qBLR1):
    qBn  = np.zeros((3, 2))
    qBn1 = np.zeros((3, 2))
    # set boundary 
    qBn[:, 0]  = bc_refrect(Qn[0, :])
    qBn[:, 1]  = bc_refrect(Qn[n-1, :])
    qBn1[:, 0] = bc_refrect(Qn1[0, :])
    qBn1[:, 1] = bc_refrect(Qn1[n-1, :])
    
    Fn  = flux(Qn , qBn, qBLR0)
    Fn1 = flux(Qn1, qBn1, qBLR1)

    Qijn  = roeQ(Qn,  qBn, qBLR0)
    Qijn1 = roeQ(Qn1, qBn1, qBLR1)
    
    # Fn  = flux(Qn , qBn, qBw0)
    # Fn1 = flux(Qn1, qBn1, qBw1)
    # Qijn  = roeQ(Qn,  qBn, qBw0)
    # Qijn1 = roeQ(Qn1, qBn1, qBw1)
    
    Fn12 = (Fn + Fn1) / 2
    Qij12 = (Qijn + Qijn1) / 2

    L = np.zeros((n, 3))
    for i in range(n):
        if ( i == obj_i_L ) or ( i == obj_i_R ):
            continue
        
        j = i
        m1 = j
        p1 = j + 1
        L[i, :] = 1/dt * ( Qn1[i, :] - dxn[i]/dxn1[i] * Qn[i, :] ) \
                + 1/dxn1[i] * ( Fn12[p1, :] - Fn12[m1, :] ) \
                - 1/dt * ( delta_x[p1]/dxn1[i] * Qij12[p1, :] - delta_x[m1]/dxn1[i] * Qij12[m1, :])

    return L

def rrk2(Q):
    def dot(a, b):
        return np.sum(a*b)
        
    Q_store = np.zeros((n, 3, Pmax))
    x_store = np.zeros((n, Pmax))
    x_e_0 = None
    retry = 50
    fixed_grid=fg
    epsilon = 10**(-14)
    _, x_e_n, dxn, _, u_B0 = update_x(Q, Q, x_e_0=None, u_B=None)
    u_B1 = u_B0
    Qn = Q # 初期値設定1
    qBLR0 = np.array([Qn[obj_i_L], Qn[obj_i_R]])
    for k in range(Nmax):        
        # dtau = set_dtau(Qn, dxn1, dt) # 内部反復の時間刻み幅の決定
        dtau = set_dtau(Qn, dxn, dt) # 内部反復の時間刻み幅の決定
        # print(np.max(delta_x))
        # iteration
        for count in range(retry + 1):
            if ( count == 0 ):
                Qn1 = Qn # 次段階の初期値はQn
                qBLR1 = qBLR0 #np.array([Qn1[obj_i-1], Qn1[obj_i+1]])
            
            # 運動方程式による物体位置/格子の更新
            x_c_n1, x_e_n1, dxn1, delta_x, u_B1_new = update_x(Qn, Qn1, x_e_n, u_B0, qBLR0, qBLR1)
            du_B1 = u_B1_new - u_B1
            u_B1 = u_B1_new

            # print(k, calc_CFL(Qn1, dxn1, dt))
            # print(u_B1)
            # rrk2 による流れ場の物理量の更新
            s1 = -dtau * calc_L(Qn1, Qn, dxn1, dxn, delta_x, dt, qBLR0, qBLR1) # s1 == g1
            s2 = -dtau * calc_L(Qn1 + c2 * s1, Qn, dxn1, dxn, delta_x, dt, qBLR0, qBLR1) # s1 == g1
            s3 = b1*s1 + b2*s2
            ss11 = dot(s1, s1)
            ss13 = dot(s1, s3)
            ss33 = dot(s3, s3)
            if ( ss33 != 0 ):
                dQ = (2*s1*ss13 - s3*ss11) / ss33
            else:
                dQ = 0
            Qn1 = Qn1 + dQ
            # 物体表面における物理量(境界条件)の更新
            qBLR1 = update_surface_q_c(Qn1, u_B1, qBLR0)
            # print(qBLR0)
            # sqrt(-1)
            Qn1[obj_i_L] = qBLR1[0]
            Qn1[obj_i_R] = qBLR1[1]
            # 残差の評価
            res_u = np.sqrt(du_B1**2)
            res_avg = np.sqrt(np.sum((dQ)**2) / (3*n))
            res_max = np.sqrt(np.max(dQ**2))
            res = max(res_avg, res_max, res_u)
            
            if ( res < epsilon ):
                break
                
            if ( count == retry ):
                print(k, "not converge")
                print(res)
                # return Q_store, x_store

        if ( k % plot_dt == 0 ):
            print(k, count, res, calc_CFL(Qn1, dxn1, dt), np.max(np.abs(Qn1[:, 1] / Qn1[:, 0]) ))
            m = int(k / plot_dt)
            Q_store[:, 0, m] = Qn1[:, 0]
            Q_store[:, 1, m] = Qn1[:, 1]
            Q_store[:, 2, m] = Qn1[:, 2]
            x_store[:, m] = x_c_n1

        # prepare for next time step
        Qn = Qn1
        x_e_n = x_e_n1
        dxn = dxn1
        u_B0 = u_B1
        qBLR0 = qBLR1
        # print(x_c_n1[obj_i_R])
        # print(qBLR1[0])
        # print(Qn[obj_left_j-1:obj_right_j+1])
        # print(qBLR1[1])
        # sqrt(-1)
        if ( qBLR1[1][0] < 0 ):
            print(u_B1)
            print(Qn1)
            print(qBLR1)
            sqrt(-1)

        
        # print(delta_x[obj_left_j-1:obj_right_j+2] / dt)
            
    return Q_store, x_store

Qsr, xsr = rrk2(Q)
    

0 13 4.915936538008367e-15 0.5263184618870593 0.0006420729566605902
100 15 9.888842416258748e-15 0.5217851359303982 0.042196660932242766
200 16 1.9509658419293934e-15 0.4900628301917032 0.06313970413916983
300 15 2.1906329669324072e-15 0.4423794680358633 0.07519505212619468
400 15 8.054498822063189e-15 0.3945610124031939 0.08264180822549515
500 13 4.8503564220264914e-15 0.3499031351628821 0.08743201923421051
600 13 1.7040590254399384e-15 0.3112038718371237 0.08941368001068473
700 12 4.5918466516389844e-15 0.27915135451583395 0.08977613910286866
800 12 2.3112784396812172e-15 0.25255200759982704 0.089750242214268
900 11 6.325078504355584e-15 0.2297068436362874 0.08932516393970814
1000 10 9.886693484355361e-15 0.21079019346433817 0.08930972855806948
1100 10 4.25368299197284e-15 0.1986661884866896 0.08927933080852224
1200 10 2.548502960861471e-15 0.19797832954509506 0.08928633129373832
1300 10 1.8910249591708094e-15 0.19729987389092238 0.08850357558724145
1400 10 1.1424132047241767e-15 0.1

In [516]:
print(Q)

[[0.125      0.         0.17857143]
 [0.125      0.         0.17857143]
 [0.125      0.         0.17857143]
 [0.125      0.         0.17857143]
 [0.125      0.         0.17857143]
 [0.125      0.         0.17857143]
 [0.125      0.         0.17857143]
 [0.125      0.         0.17857143]
 [0.125      0.         0.17857143]
 [0.125      0.         0.17857143]
 [1.         0.         1.78571429]
 [1.         0.         1.78571429]
 [1.         0.         1.78571429]
 [1.         0.         1.78571429]
 [1.         0.         1.78571429]
 [1.         0.         1.78571429]
 [1.         0.         1.78571429]
 [1.         0.         1.78571429]
 [1.         0.         1.78571429]
 [1.         0.         1.78571429]
 [1.         0.         1.78571429]
 [1.         0.         1.78571429]]


In [96]:
rho_plt = Qsr[:, 0, :]
u_plt = Qsr[:, 1, :] / Qsr[:, 0, :] 
p_plt = ( Qsr[:, 2, :] - 1/2 * rho_plt * u_plt**2 ) * g1

import matplotlib.pyplot as plt
from matplotlib.animation import ArtistAnimation
from IPython import display 

fig = plt.figure(figsize=(5,10))
ax1 = fig.add_subplot(311)
ax2 = fig.add_subplot(312)
ax3 = fig.add_subplot(313)
plt.xlim(0, 1)
#ax1.set_ylim(0, int(np.max(rho_plt)+0.5))
#ax2.set_ylim(-1, 1)
#ax3.set_ylim(0, 2)


frames = []
x = x_c
y1 = rho_plt
y2 = u_plt
y3 = p_plt
num_frames = rho_plt.shape[1]
for i in range(num_frames):
    x = xsr[:, i]
    frame1 = ax1.plot(x, y1[:, i], label='Density', color='blue')
    frame2 = ax2.plot(x, y2[:, i], label='Velocity', color='orange')
    frame3 = ax3.plot(x, y3[:, i], label='Pressure', color='green')
    
    if ( i == 0 ):
        ax1.legend()
        ax2.legend()
        ax3.legend()
    frames.append(frame1 + frame2 + frame3)
    
# 描画
ani = ArtistAnimation(fig, frames, interval=100)
html = display.HTML(ani.to_jshtml())
display.display(html)
plt.close()